"""add_toilets_table

Revision ID: 6957cc936f6b
Revises: 
Create Date: 2024-09-18 14:59:36.471707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6957cc936f6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toilets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upper_floor', sa.Boolean(), nullable=False),
    sa.Column('ladies', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.Column('accessible', sa.Boolean(), nullable=True),
    sa.Column('watchdog', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toilets_name'), 'toilets', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_toilets_name'), table_name='toilets')
    op.drop_table('toilets')
    # ### end Alembic commands ###
