"""populate_toilets

Revision ID: a410bb389543
Revises: 6957cc936f6b
Create Date: 2024-09-18 15:22:55.655871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a410bb389543'
down_revision: Union[str, None] = '6957cc936f6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from ckjz.costants import TOILETS
    from ckjz.models import Toilet
    from ckjz.engine import engine
    from sqlmodel import Session

    with Session(engine) as session:
        for toilet in TOILETS.values():
            session.add(Toilet(**toilet))
        session.commit()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
